import {useEffect,useState} from "react";import {Activity,Bot,Cpu,LayoutDashboard,MessageSquare,Settings,Sparkles,Terminal,Wifi,WifiOff} from "lucide-react";import {useStore} from "./store";import {chat,health,systemStatus} from "./api";
import {transcribeAudio,speakText} from "./voice";
import Automation from "./Automation";
import CommandCenter from "./CommandCenter";import Memory from "./Memory";

function Nav(){const{active,setActive,online}=useStore();const items=[["dashboard","Dashboard",LayoutDashboard],["chat","AI Chat",MessageSquare],["voice","Voice AI",Bot],["automation","Windows Control",Cpu],["command","Command Center",Terminal],["memory","Memory",Sparkles],["system","System",Activity],["settings","Settings",Settings]] as const;return <aside><div className="brand"><div className="logo"><Sparkles size={20}/></div><div><b>AETHER</b><small>Personal AI</small></div></div><nav>{items.map(([id,label,I])=><button className={active===id?"active":""} onClick={()=>setActive(id)} key={id}><I size={18}/>{label}</button>)}</nav><div className="online">{online?<Wifi size={15}/>:<WifiOff size={15}/>} {online?"Core Online":"Core Offline"}</div></aside>}

function Dashboard(){const{online,setActive}=useStore();const[s,setS]=useState<any>();useEffect(()=>{systemStatus().then(setS).catch(()=>{})},[]);return <section><div className="hero"><div><label>AETHER / PHASE 1</label><h1>Your personal Windows AI.</h1><p>A secure foundation for chat, automation, voice, memory and system control.</p></div><div className="orb"><Bot size={52}/></div></div><div className="cards"><Card t="AI Core" v={online?"Ready":"Starting"} d="FastAPI + provider layer"/><Card t="System" v={s?s.cpu_percent+"% CPU":"Loading"} d={s?s.memory_percent+"% memory":"Local metrics"}/><Card t="Security" v="Hardened" d="Isolated Electron bridge"/></div><div className="panel"><h2>Start with AETHER</h2><p>Configure an AI key in <code>.env</code>, then open AI Chat.</p><button onClick={()=>setActive("chat")}>Open AI Chat</button></div></section>}
function Card({t,v,d}:{t:string;v:string;d:string}){return <div className="card"><span>{t}</span><strong>{v}</strong><small>{d}</small></div>}
function Chat(){const{messages,add,clear}=useStore();const[q,setQ]=useState("");const[busy,setBusy]=useState(false);const[err,setErr]=useState("");async function send(){const x=q.trim();if(!x||busy)return;setQ("");setErr("");add({id:crypto.randomUUID(),role:"user",content:x});setBusy(true);try{const d=await chat(x,[...messages,{id:"",role:"user",content:x}].map(m=>({role:m.role,content:m.content})));add({id:crypto.randomUUID(),role:"assistant",content:d.content})}catch(e){setErr(e instanceof Error?e.message:"Request failed")}finally{setBusy(false)}}return <section className="chat"><div className="head"><div><label>AI CHAT</label><h1>Talk to AETHER</h1></div><button className="ghost" onClick={clear}>New Chat</button></div><div className="messages">{messages.length===0&&<div className="empty"><Bot size={34}/><h2>How can I help?</h2><p>Ask a question or plan your next task.</p></div>}{messages.map(m=><div className={"bubble "+m.role} key={m.id}><small>{m.role==="user"?"You":"AETHER"}</small><p>{m.content}</p></div>)}{busy&&<div className="bubble assistant"><small>AETHER</small><p>Thinking…</p></div>}</div>{err&&<div className="error">{err}</div>}<div className="composer"><textarea value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();send()}}} placeholder="Message AETHER…"/><button onClick={send} disabled={busy}>Send</button></div></section>}
function Voice(){const[recording,setRecording]=useState(false);const[busy,setBusy]=useState(false);const[text,setText]=useState("");const[err,setErr]=useState("");const recorder=useState<{r:MediaRecorder|null;chunks:Blob[]}>({r:null,chunks:[]})[0];async function start(){setErr("");setText("");if(!navigator.mediaDevices?.getUserMedia){setErr("اس نظام میں مائیکروفون دستیاب نہیں۔");return}try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});const r=new MediaRecorder(stream);recorder.r=r;recorder.chunks=[];r.ondataavailable=e=>{if(e.data.size)recorder.chunks.push(e.data)};r.onstop=async()=>{stream.getTracks().forEach(t=>t.stop());setBusy(true);try{const blob=new Blob(recorder.chunks,{type:r.mimeType||"audio/webm"});const d=await transcribeAudio(blob);setText(d.text||"");}catch(e){setErr(e instanceof Error?e.message:"Transcription failed")}finally{setBusy(false)}};r.start();setRecording(true)}catch(e){setErr(e instanceof Error?e.message:"Microphone permission failed")}}function stop(){if(recorder.r&&recorder.r.state!=="inactive"){recorder.r.stop();setRecording(false)}}async function speak(){if(!text.trim())return;setErr("");try{const blob=await speakText(text);const url=URL.createObjectURL(blob);const audio=new Audio(url);audio.onended=()=>URL.revokeObjectURL(url);await audio.play()}catch(e){setErr(e instanceof Error?e.message:"TTS failed")}}return <section><div className="head"><div><label>VOICE AI / PHASE 2</label><h1>Talk to AETHER</h1><p>مقامی Whisper اور Windows TTS — کوئی paid API لازمی نہیں۔</p></div></div><div className="panel"><div className="voice-actions"><button onClick={recording?stop:start}>{recording?"⏹ ریکارڈنگ روکیں":"🎙 مائیکروفون شروع کریں"}</button><button onClick={speak} disabled={busy||!text.trim()}>🔊 آواز میں سنائیں</button></div><textarea value={text} onChange={e=>setText(e.target.value)} placeholder="آپ کی آواز کا متن یہاں آئے گا…" rows={7}/>{busy&&<p>آواز کو مقامی Whisper سے تبدیل کیا جا رہا ہے…</p>}{err&&<div className="error">{err}</div>}<p className="muted">پہلی بار Whisper ماڈل ڈاؤن لوڈ ہونے میں وقت اور انٹرنیٹ لگ سکتا ہے۔ بعد میں ماڈل مقامی طور پر چلتا ہے۔</p></div></section>}

function System(){const[s,setS]=useState<any>();useEffect(()=>{const f=()=>systemStatus().then(setS).catch(()=>{});f();const t=setInterval(f,2000);return()=>clearInterval(t)},[]);const a=[["CPU",s?.cpu_percent+"%"],["Memory",s?.memory_percent+"%"],["Disk",s?.disk_percent+"%"],["OS",s?.os],["Python",s?.python_version],["Backend",s?"Online":"—"]];return <section><div className="head"><div><label>SYSTEM MONITOR</label><h1>Windows health</h1></div></div><div className="cards">{a.map(x=><div className="metric" key={x[0]}><span>{x[0]}</span><strong>{x[1]||"—"}</strong></div>)}</div></section>}
function SettingsPage(){return <section><label>SETTINGS</label><h1>AETHER configuration</h1><div className="panel"><h2>AI Provider</h2><p>Use environment variables. Secrets never belong in the frontend or Git.</p><code>OPENAI_API_KEY=your_key</code><code>GEMINI_API_KEY=your_key</code><p>See README for setup.</p></div></section>}
export default function App(){const{active,setOnline}=useStore();useEffect(()=>{health().then(()=>setOnline(true)).catch(()=>setOnline(false))},[]);return <div className="app"><Nav/><main><header><span>AETHER</span><span>● Phase 3 Windows Control</span></header>{active==="dashboard"?<Dashboard/>:active==="chat"?<Chat/>:active==="voice"?<Voice/>:active==="automation"?<Automation/>:active==="command"?<CommandCenter/>:active==="memory"?<Memory/>:active==="system"?<System/>:<SettingsPage/>}</main></div>}
