import {useEffect,useRef,useState} from "react";import {Activity,Bot,Cpu,LayoutDashboard,MessageSquare,Settings,Sparkles,Terminal,Wifi,WifiOff} from "lucide-react";import {useStore} from "./store";import {chat,health,systemStatus} from "./api";
import {chatForVoice,speakText,stopSpeaking,transcribeAudio} from "./voice";
import Automation from "./Automation";
import CommandCenter from "./CommandCenter";import Memory from "./Memory";import TradingLab from "./TradingLab";

function Nav(){const{active,setActive,online}=useStore();const items=[["dashboard","Dashboard",LayoutDashboard],["chat","AI Chat",MessageSquare],["voice","Voice AI",Bot],["automation","Windows Control",Cpu],["command","Command Center",Terminal],["memory","Memory",Sparkles],["trading","Trading Lab",Sparkles],["system","System",Activity],["settings","Settings",Settings]] as const;return <aside><div className="brand"><div className="logo"><Sparkles size={20}/></div><div><b>AETHER</b><small>Personal AI</small></div></div><nav>{items.map(([id,label,I])=><button className={active===id?"active":""} onClick={()=>setActive(id)} key={id}><I size={18}/>{label}</button>)}</nav><div className="online">{online?<Wifi size={15}/>:<WifiOff size={15}/>} {online?"Core Online":"Core Offline"}</div></aside>}

function Dashboard(){const{online,setActive}=useStore();const[s,setS]=useState<any>();useEffect(()=>{systemStatus().then(setS).catch(()=>{})},[]);return <section><div className="hero"><div><label>AETHER / PHASE 1</label><h1>Your personal Windows AI.</h1><p>A secure foundation for chat, automation, voice, memory and system control.</p></div><div className="orb"><Bot size={52}/></div></div><div className="cards"><Card t="AI Core" v={online?"Ready":"Starting"} d="FastAPI + provider layer"/><Card t="System" v={s?s.cpu_percent+"% CPU":"Loading"} d={s?s.memory_percent+"% memory":"Local metrics"}/><Card t="Security" v="Hardened" d="Isolated Electron bridge"/></div><div className="panel"><h2>Start with AETHER</h2><p>Configure an AI key in <code>.env</code>, then open AI Chat.</p><button onClick={()=>setActive("chat")}>Open AI Chat</button></div></section>}
function Card({t,v,d}:{t:string;v:string;d:string}){return <div className="card"><span>{t}</span><strong>{v}</strong><small>{d}</small></div>}
function Chat(){const{messages,add,clear}=useStore();const[q,setQ]=useState("");const[busy,setBusy]=useState(false);const[err,setErr]=useState("");async function send(){const x=q.trim();if(!x||busy)return;setQ("");setErr("");add({id:crypto.randomUUID(),role:"user",content:x});setBusy(true);try{const d=await chat(x,[...messages,{id:"",role:"user",content:x}].map(m=>({role:m.role,content:m.content})));add({id:crypto.randomUUID(),role:"assistant",content:d.content})}catch(e){setErr(e instanceof Error?e.message:"Request failed")}finally{setBusy(false)}}return <section className="chat"><div className="head"><div><label>AI CHAT</label><h1>Talk to AETHER</h1></div><button className="ghost" onClick={clear}>New Chat</button></div><div className="messages">{messages.length===0&&<div className="empty"><Bot size={34}/><h2>How can I help?</h2><p>Ask a question or plan your next task.</p></div>}{messages.map(m=><div className={"bubble "+m.role} key={m.id}><small>{m.role==="user"?"You":"AETHER"}</small><p>{m.content}</p></div>)}{busy&&<div className="bubble assistant"><small>AETHER</small><p>Thinking…</p></div>}</div>{err&&<div className="error">{err}</div>}<div className="composer"><textarea value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();send()}}} placeholder="Message AETHER…"/><button onClick={send} disabled={busy}>Send</button></div></section>}

function Voice(){const[recording,setRecording]=useState(false);const[busy,setBusy]=useState(false);const[status,setStatus]=useState("تیار");const[text,setText]=useState("");const[answer,setAnswer]=useState("");const[err,setErr]=useState("");const recorderRef=useRef<MediaRecorder|null>(null);const streamRef=useRef<MediaStream|null>(null);const chunksRef=useRef<Blob[]>([]);const audioRef=useRef<HTMLAudioElement|null>(null);const historyRef=useRef<{role:"user"|"assistant";content:string}[]>([]);

useEffect(()=>()=>{streamRef.current?.getTracks().forEach(t=>t.stop());audioRef.current?.pause();stopSpeaking()},[]);

async function start(){if(recording||busy)return;setErr("");setText("");setAnswer("");setStatus("مائیکروفون آن ہے — بولیں…");if(!navigator.mediaDevices?.getUserMedia){setErr("اس سسٹم میں مائیکروفون دستیاب نہیں۔");return}try{const stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true}});streamRef.current=stream;const mime=MediaRecorder.isTypeSupported("audio/webm;codecs=opus")?"audio/webm;codecs=opus":"audio/webm";const r=new MediaRecorder(stream,{mimeType:mime});recorderRef.current=r;chunksRef.current=[];r.ondataavailable=e=>{if(e.data.size)chunksRef.current.push(e.data)};r.onerror=()=>setErr("مائیکروفون ریکارڈنگ میں مسئلہ آیا۔");r.onstop=()=>{stream.getTracks().forEach(t=>t.stop());streamRef.current=null;void processRecording(r.mimeType||"audio/webm")};r.start();setRecording(true)}catch(e){setStatus("تیار");setErr(e instanceof Error?e.message:"Microphone permission failed")}}

function stop(){const r=recorderRef.current;if(r&&r.state!=="inactive"){setStatus("آواز تیار کی جا رہی ہے…");r.stop();setRecording(false)}}

async function processRecording(mimeType:string){setBusy(true);setErr("");try{const blob=new Blob(chunksRef.current,{type:mimeType||"audio/webm"});const transcript=await transcribeAudio(blob);const spoken=transcript.text.trim();if(!spoken){setStatus("کوئی واضح آواز نہیں ملی۔ دوبارہ کوشش کریں۔");return}setText(spoken);setStatus("AETHER سوچ رہا ہے…");const response=await chatForVoice(spoken,historyRef.current);const spokenAnswer=response.content.trim();setAnswer(spokenAnswer);historyRef.current=[...historyRef.current,{role:"user",content:spoken},{role:"assistant",content:spokenAnswer}].slice(-20);setStatus("AETHER جواب دے رہا ہے…");const audioBlob=await speakText(spokenAnswer);const url=URL.createObjectURL(audioBlob);audioRef.current?.pause();const audio=new Audio(url);audioRef.current=audio;audio.onended=()=>{URL.revokeObjectURL(url);setStatus("تیار — دوبارہ بولیں")};audio.onerror=()=>{URL.revokeObjectURL(url);setErr("AETHER کا آڈیو جواب چل نہیں سکا۔");setStatus("تیار")};await audio.play()}catch(e){setStatus("تیار");setErr(e instanceof Error?e.message:"Voice conversation failed")}finally{setBusy(false)}}

function stopAudio(){audioRef.current?.pause();audioRef.current?.currentTime=0;stopSpeaking();setStatus("تیار")}

return <section><div className="head"><div><label>VOICE AI / FULL CONVERSATION</label><h1>Speak to AETHER</h1><p>آپ بولیں → مقامی Whisper آواز کو متن میں بدلے گا → AETHER جواب دے گا → Windows TTS جواب بلند آواز میں سنائے گا۔</p></div><button className="ghost" onClick={stopAudio}>🔇 آواز روکیں</button></div><div className="panel voice-panel"><div className="voice-orb">{recording?"🎙️":"✦"}</div><div className="voice-status">{status}</div><div className="voice-actions"><button onClick={recording?stop:start} disabled={busy}>{recording?"⏹️ ریکارڈنگ روکیں":"🎙️ بولنے کے لیے کلک کریں"}</button><button className="ghost" onClick={stopAudio} disabled={!audioRef.current}>🔇 Stop</button></div><div className="voice-result"><div><small>آپ نے کہا</small><p>{text||"—"}</p></div><div><small>AETHER نے جواب دیا</small><p>{answer||"—"}</p></div></div>{busy&&<p className="muted">مقامی Whisper → AI Core → Windows TTS pipeline چل رہی ہے…</p>}{err&&<div className="error">{err}</div>}<p className="muted">STT: Local Faster-Whisper • TTS: Windows SAPI/pyttsx3 • Paid voice API ضروری نہیں۔ پہلی بار Whisper model download ہو سکتا ہے۔</p></div></section>}

function System(){const[s,setS]=useState<any>();useEffect(()=>{const f=()=>systemStatus().then(setS).catch(()=>{});f();const t=setInterval(f,2000);return()=>clearInterval(t)},[]);const a=[["CPU",s?.cpu_percent+"%"],["Memory",s?.memory_percent+"%"],["Disk",s?.disk_percent+"%"],["OS",s?.os],["Python",s?.python_version],["Backend",s?"Online":"—"]];return <section><div className="head"><div><label>SYSTEM MONITOR</label><h1>Windows health</h1></div></div><div className="cards">{a.map(x=><div className="metric" key={x[0]}><span>{x[0]}</span><strong>{x[1]||"—"}</strong></div>)}</div></section>}
function SettingsPage(){return <section><label>SETTINGS</label><h1>AETHER configuration</h1><div className="panel"><h2>AI Provider</h2><p>Use environment variables. Secrets never belong in the frontend or Git.</p><code>OPENAI_API_KEY=your_key</code><code>GEMINI_API_KEY=your_key</code><p>See README for setup.</p></div></section>}
export default function App(){const{active,setOnline}=useStore();useEffect(()=>{health().then(()=>setOnline(true)).catch(()=>setOnline(false))},[]);return <div className="app"><Nav/><main><header><span>AETHER</span><span>● Voice Command Pipeline</span></header>{active==="dashboard"?<Dashboard/>:active==="chat"?<Chat/>:active==="voice"?<Voice/>:active==="automation"?<Automation/>:active==="command"?<CommandCenter/>:active==="memory"?<Memory/>:active==="trading"?<TradingLab/>:active==="system"?<System/>:<SettingsPage/>}</main></div>}
